# Generated by Django 2.2.5 on 2019-09-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='本の奥付に書いてある書籍名を入力してください。', max_length=200, verbose_name='書籍名')),
                ('author', models.CharField(blank=True, help_text='本の奥付に書いてある著者名を入力してください。', max_length=200, null=True, verbose_name='著者名')),
                ('publisher', models.CharField(blank=True, help_text='本の奥付に書いてある出版社を入力してください。', max_length=200, null=True, verbose_name='出版社')),
                ('published_date', models.DateField(blank=True, help_text='本の奥付に書いてある出版日を入力してください。', null=True, verbose_name='出版日')),
                ('version', models.CharField(blank=True, help_text='本の奥付に書いてある版数を入力してください。', max_length=200, null=True, verbose_name='版数')),
                ('isbn', models.BigIntegerField(blank=True, help_text='本の奥付に書いてあるISBNを入力してください。ISBNとは13桁の97から始まるコードです。', null=True, verbose_name='ISBN')),
                ('text', models.TextField(blank=True, help_text='宣伝文を入力してください。', null=True, verbose_name='宣伝文')),
                ('state', models.IntegerField(choices=[(1, 'とても良い'), (2, '良い'), (3, 'あまり良くない'), (4, '良くない')], default=1, verbose_name='状態')),
            ],
        ),
    ]
