# Generated by Django 2.2.5 on 2019-10-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_book_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('undergraduate', models.IntegerField(choices=[(1, '共通科目'), (2, '外国語科目'), (3, '健康余暇科学科目'), (4, '英語英文学科'), (5, '国際関係学科'), (6, '数学科'), (7, '情報科学科')], default=1, verbose_name='学部')),
                ('course', models.CharField(help_text='該当授業の科目名を入力してください。', max_length=200, verbose_name='科目名')),
                ('instructor', models.CharField(blank=True, help_text='該当授業の担当教員名を入力してください。', max_length=200, null=True, verbose_name='担当教員名')),
                ('term', models.IntegerField(choices=[(1, '1ターム'), (2, '２ターム'), (3, '３ターム'), (4, '４ターム')], default=1, verbose_name='ターム')),
                ('dayOfTheWeek', models.IntegerField(choices=[(1, '月曜'), (2, '火曜'), (3, '水曜'), (4, '木曜'), (5, '金曜')], default=1, verbose_name='曜日')),
                ('period', models.IntegerField(choices=[(1, '1限'), (2, '2限'), (3, '3限'), (4, '4限'), (5, '5限'), (6, '6限')], default=1, verbose_name='時限')),
                ('yearOfStudy', models.IntegerField(choices=[(1, '1年'), (2, '2年'), (3, '3年'), (4, '4年')], default=1, verbose_name='推奨レベル')),
            ],
        ),
    ]
